extends:
  - eslint:recommended
  - google
env:
  es2021: true
  node: true
  mocha: true
  browser: false
  jest: true
parserOptions:
  sourceType: module
rules:
  space-in-parens:
    - error
    - never
