openapi: '3.0.0'
info:
  version: 1.0.0
  title: Warehouse service
  license:
    name: MIT
servers:
  - url: /
    description: Localhost
paths:
  /health:
    get:
      summary: Get API health information
      tags:
        - retention
      x-router-controller: healthController
      operationId: getStatus
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/health'

  /products/{productId}:
    delete:
      summary: Remove(Sell) a product and update inventory
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: Numeric ID of the product to delete
      tags:
        - retention
      x-router-controller: productController
      operationId: sell
      responses:
        '204':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/health'

  /products:
    get:
      summary: Get all products and quantity of each that is an available with the current inventory
      tags:
        - retention
      x-router-controller: productController
      operationId: getAll
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productList'
components:
  schemas:
    health:
      type: object
      properties:
        status:
          type: string
    productList:
      type: array
      items:
        $ref: '#/components/schemas/products'
    products:
      type: object
      properties:
        name:
          type: string
        contain_articles:
          type: array
          items:
            $ref: '#/components/schemas/inventory'
    inventory:
      type: object
      properties:
        art_id:
          type: string
        name: 
          type: string
        amount_of:
          type: string
        stock:
          type: string

